POST http://localhost:3333/manga
Content-Type: application/json

{
    "obra": "Kagurabachi",
    "mangaka": "Takeru Hokazono",
    "quantidade_volume": 1
}

###

GET http://localhost:3333/manga

###

GET http://localhost:3333/manga?search=Doron

###

PUT http://localhost:3333/manga/e7ed37fe-02bd-45a0-8c9f-cfb0be82cb6e
Content-Type: application/json

{
    "obra": "Doron Dororon",
    "mangaka": "Gen Osuka",
    "quantidade_volume": 5
}

###

DELETE http://localhost:3333/manga/e7ed37fe-02bd-45a0-8c9f-cfb0be82cb6e
